# Generated by Django 5.2 on 2026-09-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("PPO", "PPO"),
                            ("HMO", "HMO"),
                            ("EPO", "EPO"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("deductible", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coinsurance_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "out_of_pocket_max",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("netid", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "insurance_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient",
                        to="claims.insuranceplan",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "network_status",
                    models.CharField(
                        choices=[("IN", "In Network"), ("OUT", "Out of Network")],
                        max_length=3,
                    ),
                ),
                (
                    "insurance_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="providers",
                        to="claims.insuranceplan",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_number", models.CharField(max_length=50)),
                ("bill_date", models.DateField()),
                (
                    "insurance_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="claims.insuranceplan",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="claims.patient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="claims.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="BillLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=200)),
                ("procedure_reference", models.CharField(blank=True, max_length=50)),
                (
                    "charged_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_covered_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estimated_patient_responsibility",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="claims.bill",
                    ),
                ),
            ],
            options={
                "ordering": ["bill", "line_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bill", "line_number"),
                        name="unique_line_number_per_bill",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="provider",
            constraint=models.UniqueConstraint(
                fields=("name", "insurance_plan"), name="unique_provider_per_plan"
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("patient", "reference_number"),
                name="unique_bill_reference_per_patient",
            ),
        ),
    ]
